/* Generated by build_narration_manifest.js - do not edit. */
window.ANTARA_NARRATION_MANIFEST = {
  "version": 1,
  "generatedAt": "2026-08-24T09:51:08.484Z",
  "generatedBy": "build_narration_manifest.js",
  "note": "Generated file - do not hand-edit. Add audio under audio/manuscripts/ and re-run npm run build:narration.",
  "languages": [
    {
      "code": "sa",
      "label": "Sanskrit",
      "nativeLabel": "संस्कृतम्",
      "textField": "sanskrit",
      "speech": null
    },
    {
      "code": "hi",
      "label": "Hindi",
      "nativeLabel": "हिन्दी",
      "textField": "hindi",
      "speech": {
        "lang": "hi-IN",
        "match": [
          "hi-in",
          "hi"
        ]
      }
    },
    {
      "code": "en",
      "label": "English",
      "nativeLabel": "English",
      "textField": "english",
      "speech": {
        "lang": "en-IN",
        "match": [
          "en-in",
          "en-gb",
          "en-us",
          "en"
        ]
      }
    },
    {
      "code": "ta",
      "label": "Tamil",
      "nativeLabel": "தமிழ்",
      "textField": null,
      "speech": null
    },
    {
      "code": "te",
      "label": "Telugu",
      "nativeLabel": "తెలుగు",
      "textField": null,
      "speech": null
    },
    {
      "code": "gu",
      "label": "Gujarati",
      "nativeLabel": "ગુજરાતી",
      "textField": null,
      "speech": null
    },
    {
      "code": "mr",
      "label": "Marathi",
      "nativeLabel": "मराठी",
      "textField": null,
      "speech": null
    },
    {
      "code": "bn",
      "label": "Bengali",
      "nativeLabel": "বাংলা",
      "textField": null,
      "speech": null
    },
    {
      "code": "kn",
      "label": "Kannada",
      "nativeLabel": "ಕನ್ನಡ",
      "textField": null,
      "speech": null
    },
    {
      "code": "ml",
      "label": "Malayalam",
      "nativeLabel": "മലയാളം",
      "textField": null,
      "speech": null
    },
    {
      "code": "pa",
      "label": "Punjabi",
      "nativeLabel": "ਪੰਜਾਬੀ",
      "textField": null,
      "speech": null
    },
    {
      "code": "or",
      "label": "Odia",
      "nativeLabel": "ଓଡ଼ିଆ",
      "textField": null,
      "speech": null
    }
  ],
  "resolutionOrder": [
    "verse",
    "chapter",
    "book"
  ],
  "tracks": {}
};
